name: Test Dotfiles Installation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-linux-dotfiles:
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
            - os: ubuntu20-04
              ubuntu_version: "20.04"
              dockerfile_path: "LinuxUbuntu"
            - os: ubuntu22-04
              ubuntu_version: "22.04"
              dockerfile_path: "LinuxUbuntu"
            - os: ubuntu24-04
              ubuntu_version: "24.04"
              dockerfile_path: "LinuxUbuntu"
            - os: rocky8
              ubuntu_version: "8"  # Assuming Rocky uses "8"
              dockerfile_path: "LinuxRocky8"
              
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image for ${{ matrix.os }}
        run: |
          docker build \
            --build-arg UBUNTU_VERSION=${{ matrix.ubuntu_version }} \
            --build-arg GIT_BRANCH=${{ github.head_ref }} \
            -t dotfiles-test-image-${{ matrix.os }} \
            -f tests/${{ matrix.dockerfile_path }}/Dockerfile .

      - name: Installing dotfiles and verifying successful installation
        run: |
          docker run --rm dotfiles-test-image-${{ matrix.os }} \
            bash -c "chezmoi apply && echo 'SUCCESSFUL INSTALL' || (echo 'INSTALL FAILED'; exit 1)"

  test-macos-dotfiles:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ChezMoi & Apply Dotfiles
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)"
          chezmoi -S $(pwd) init --apply

  test-windows-dotfiles:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Chezmoi
        run: iex "& { $(irm https://get.chezmoi.io/ps1) } -b '$env:RUNNER_TEMP/bin'"
      - name: Apply dotfiles
        run: $env:RUNNER_TEMP\bin\chezmoi.exe init -S $PWD --apply hmvege
      - name: Idempotency check
        run: |
          $env:RUNNER_TEMP\bin\chezmoi.exe apply -n | Tee-Object diff.txt
          if ((Get-Content diff.txt).Length -ne 0) { throw 'Not idempotent!' }
